---
name: SVN-Notify
version: 2.77
author:
  - 'David E. Wheeler <david@kineticode.com>'
abstract: Subversion activity notification
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  Getopt::Long: 2.34
  perl: 5.006
build_requires:
  File::Spec: 0
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  File::Spec: 0
  HTML::Entities: 0
  Net::SMTP: 0
  Net::SMTP_auth: 0
  Pod::Usage: 1.33
  Test::Pod: 1.2
  Test::Pod::Coverage: 1.06
  Text::Trac: 0.10
provides:
  SVN::Notify:
    file: lib/SVN/Notify.pm
    version: 2.77
  SVN::Notify::Alternative:
    file: lib/SVN/Notify/Alternative.pm
    version: 1.0
  SVN::Notify::Filter::Trac:
    file: lib/SVN/Notify/Filter/Trac.pm
    version: 2.77
  SVN::Notify::HTML:
    file: lib/SVN/Notify/HTML.pm
    version: 2.77
  SVN::Notify::HTML::ColorDiff:
    file: lib/SVN/Notify/HTML/ColorDiff.pm
    version: 2.77
  SVN::Notify::SMTP:
    file: lib/SVN/Notify.pm
generated_by: Module::Build version 0.280802
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
